### ISSUE TITLE
Discussion: add .join() calls in finally block?

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#296] opened 2018-11-16 13:37 UTC
Calls to `.join()` are not in a finally block:

https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/Association.py#L623
https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/DataDrivenRelation.py#L697

what will be the consequence of this if there is an error between the .start() and the .join() calls?

**Comment by afaulconbridge** [comment] 2018-11-16 13:53
Closing for two reasons. Firstly, this is a duplicate of opentargets/platform#177. Secondly, this will be (eventaully) resolved with the same technique as opentargets/platform#282 i.e. use of https://cgarciae.github.io/pypeln/

**Closed by afaulconbridge** 2018-11-16 13:53 UTC
Labels: Kind: Bug

**Comment by pieterlukasse** [comment] 2018-11-16 14:00
ok, thanks for the links :+1:
