### ISSUE TITLE
UniProt Gene Association Issue

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#801] opened 2020-01-06 15:21 UTC
I noticed recently that evidence records are dropped (@[data_pipeline/LookupTables.py#L114](https://github.com/opentargets/data_pipeline/blob/f4c9886b9b9613d3dbc309b6fa0f88145254431a/mrtarget/common/LookupTables.py#L114)) if the target id is a UniProt accession related to multiple ensembl genes.  Was there a specific reason for that?  

For example, [SMN1](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000172062;r=5:70925030-70953942) and [SMN2](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000205571;r=5:70049612-70078522) are both associated with a single UniProt accession, [Q16637](https://www.uniprot.org/uniprot/Q16637#gene_name_table), but are dropped by the pipeline despite having valid disease associations.  There are ~50 UniProt evidence records and ~1.3k EuropePMC records with this accession but none of them make it onto the [SMN1](https://www.targetvalidation.org/target/ENSG00000172062/associations) or [SMN2](https://www.targetvalidation.org/target/ENSG00000205571/associations) OT Platform pages.

Broadening that search a bit, I'm seeing that there are 76 **primary** UniProt accessions (i.e. not secondary accessions that may have been merged by UniProt in the past) associated with multiple genes that would never see data integrated for at least the chembl, uniprot, uniprot_literature, and europepmc sources.  There are then about 22k europepmc, ~50 chembl, and ~50 uniprot/uniprot_literature evidence records being lost in total across these accessions.

I also didn't see anything about that in the [spreadsheet](https://docs.google.com/spreadsheets/d/1yo2_cW__upXmQfQp1CiGwJqnO611WvzjBTTMH4-9JNI/edit#gid=0) you mentioned @d0choa, so I thought I'd point it out if it wasn't an intentional consequence of that code.

**Comment by d0choa** [comment] 2020-01-06 16:01
I agree with you that we should rescue the aforementioned evidence. Ignoring the one-2-many relationships is an oversimplification. @cmalangone can you have a look?

**Comment by cmalangone** [comment] 2020-01-07 11:29
The evidences are created properly. During the step of validation these evidences are excluded and stored in the invalid-evidence index. https://github.com/opentargets/data_pipeline/blob/f4c9886b9b9613d3dbc309b6fa0f88145254431a/mrtarget/modules/Evidences.py#L234 
The index invalid-evidence index showed us the list of evidences that @eric-czech mentioned above. 
(strings with the explanation Multiple genes with uniprot ...)
 
So we are evaluating  the impact of not excluding them.

**Comment by d0choa** [comment] 2020-01-07 13:11
The conclusion is that the one-2-one assumption was made when the pipeline was developed as a simplification.

The truth is that biologically speaking it would be more correct to do a one-2-many mapping and duplicate the evidence for every Ensembl ID. @AsierGonzalez has looked at what's the cause of the one-2-many relationships and it seems they are mostly caused by gene paralogs encoding very similar protein products. In the most extreme case, the H4 histone has 14 different Ensembl IDs for one single Uniprot ID. The difference is due to the different philosophies to define what's a gene and what's a protein by the 2 resources. While we keep them all in the gene index, evidences are considered invalid. This problem affects only datasources that are based on uniprot IDs: europepmc, chembl and uniprot / uniprot_literature / uniprot_somatic.

In order to fix the problem in the current pipeline, we need to explore other functions where this assumption is made. @cmalangone is having a deeper look. Although, the issue is important for us, it's also a part of the pipeline flagged to be refactored. @eric-czech we are looking closely at your progress in this area and thanks for flagging the issue.

**Comment by eric-czech** [comment] 2020-01-07 14:45
Thanks for the update guys!  Happy to help.

**Comment by AsierGonzalez** [comment] 2020-01-07 15:41
Hi, this is a summary of what I have found looking into the [19.11 target file](https://storage.googleapis.com/open-targets-data-releases/19.11/output/19.11_target_list.csv.gz):

- General target stats:

| Targets | Targets with UniProt mapping  | Unique UniProt accessions | Duplicate Uniprot accessions | Duplicate primary UniProt accessions |
| :---: | :---: | :---: | :---: | :---: |
| 60,564 | 20,092 | 40,472 | 368 |  |

- Duplicate Uniprot accession stats:

| Targets with duplicate UniProt accessions | Duplicate Uniprot accessions | Duplicate primary UniProt accessions |
| :---: | :---: | :---: |
| 841 | 368 | 289  |

I have checked how many times the most repeated accessions appear to see if any had hundreds of genes that would exponentially increase the number of evidence if we decided to duplicate them, which does not seem to be the case. See the table below for the top ten UniProt accessions and their counts (full list in the attached _duplicate_uniprot_counts.txt_ file):

| Uniprot accession | Target counts |
| --- | --- |
| P62805 | 14 |
| Q5JQC4 | 12 |
| P68431 | 8 |
| Q0WX57 | 7 |
| Q9ULZ0 | 6 |
| P0C0S8 | 5 |
| Q8N7V5 | 5 |
| P62807 | 5 |
| A1L429 | 4 |

I have also looked into what the duplicate accessions are (see attached _duplicate_uniprot_info.txt_ file) and most of them seem to be big protein families, e.g. histones or ubiquitin, or obsolote secondary accessions :

| Uniprot accession | Protein name |
| --- | --- |
| P62805 | Histone H4 |
| Q5JQC4 |  Cancer/testis antigen 47A |
| P68431 | Histone H3.1 |
| Q0WX57 | Ubiquitin carboxyl-terminal hydrolase 17-like protein 24 |
| Q9ULZ0 | TP53-target gene 3 protein |
| P0C0S8 | Histone H2A type 1 |
| Q8N7V5 | Proline-rich protein 20A; Proline-rich protein 20E; Proline-rich protein 20C; Proline-rich protein 20D, Proline-rich protein 20B |
| P62807 | Histone H2B type 1-C/E/F/G/I |
| A1L429 | G antigen 12B/C/D/E |

I'd say that these many-to-many relationships are  biologically relevant and that we should try to handle them.

[duplicate_uniprot_counts.txt](https://github.com/opentargets/platform/files/4031329/duplicate_uniprot_counts.txt)
[duplicate_uniprot_info.txt](https://github.com/opentargets/platform/files/4031330/duplicate_uniprot_info.txt)

**Comment by mkarmona** [comment] 2020-02-06 14:16
@eric-czech thank you very much for highlighting this problem. Indeed, this is a bug a bit difficult to correct in the current pipeline so I coded a temporal fix that runs before the associations reach the pipeline. Basically the algo does this

1. build the inversed LUT for each protein accession the corresponding genes
2. if one evidence belonging to the multi-gene case is found then 
3. duplicate the evidence replacing the protein id by the gene ids and add to the unique fields the corresponding geneid in order to make unique the evidence
4. write all back to `jsonl.gz` but partition by the data source.

Here you have the [aforementioned script](https://github.com/opentargets/platform-etl-backend/blob/master/backend/evidenceProteinFix.sc) that implements the above recipe. Would you mind confirming you are following the same algorithm on your side? I mean, 

> you correct the evidence transforming it from an evidence row identified by a protein id into a set of _n_ evidence rows with the corrected fields in order to be unique and identifiable as targets

**Comment by eric-czech** [comment] 2020-02-14 14:26
Hey @mkarmona thanks for the update.  I removed the part of the Spark version of the pipeline that was eliminating UniProt accessions with multiple gene associations, but is there any reason not to try to add the gene id (in addition to the accession) to the unique_association_fields somewhere upstream like [here](https://github.com/ebi-uniprot/open-targets-core-db/blob/master/src/main/java/uk/ac/ebi/uniprot/ot/model/factory/GeneticsRootFactory.java#L92) instead?  Assuming that's the correct code, it doesn't look like it would be difficult to account for this. 

Would you guys agree that's the correct place for a long-term solution?  I'm sure @eddturner has more important things on his plate but I'd happily start a conversation about getting it fixed in that repo (and maybe push up a PR).

**Comment by AsierGonzalez** [comment] 2020-02-19 15:05
After the 20.02 pipeline run both SMN1 and SMN2 have UniProt and text mining evidence.

**19.11**
![Screenshot 2020-02-19 at 15.02.43.png](https://images.zenhubusercontent.com/5e3bdd3b5ae31307fec27bc8/586ab190-b80f-4002-ba29-fc9acdd85801)

**20.02 (QA)**
![Screenshot 2020-02-19 at 15.02.29.png](https://images.zenhubusercontent.com/5e3bdd3b5ae31307fec27bc8/4effaf89-5cae-47ea-8c2f-29aa4bbe99e5)

**Comment by d0choa** [comment] 2020-02-19 15:53
The bug is fixed according to @AsierGonzalez comment. I'm closing the issue accordingly.

However, the solution is not optimal as it's requiring to apply a post-processing to the evidences, in order to explode the uniprot -> Ensembl mappings. For the moment, we'll keep this as it's the only way we can assure it's done consistently across the 3 problematic datasources. Long-term, we'll work with them to resolve to Ensembl IDs their uniprot identifiers.

**Closed by d0choa** 2020-02-19 15:53 UTC

**Comment by hammer** [comment] 2020-02-24 15:00
@d0choa is there an issue file upstream to track the long-term fix for this issue?

**Comment by d0choa** [comment] 2020-02-24 15:36
We will encapsulate this task in a bigger epic aimed to review the data submission guidelines across providers #855. Feedback is appreciated
