### ISSUE TITLE
Protein information panel "Variants" track sometimes not shown

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#596] opened 2019-05-13 16:28 UTC
For some genes the "Variants" track on "Protein information" panel will not show.

Steps to reproduce:
1. go to https://www.targetvalidation.org/target/ENSG00000139618
2. the last track "Variants" will sometimes not load

tested on a low end Lenovo laptop with Windows 7 (_not_ my laptop in case you are wondering)

**Comment by d0choa** [comment] 2020-01-29 17:31
Not able to reproduce. Probably fixed by ProtVista team

**Closed by d0choa** 2020-01-29 17:31 UTC
