### ISSUE TITLE
Drug index: Investigate other options for adverse events on drug page

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#74] opened 2018-08-15 09:31 UTC
We currently display OpenFDA AEs that we retrieve via an API call directly to FDA endpoint.

- [ ] Normalise by prescription rates

- [ ] Look at drugcentral and how they get clinically reported AEs (from drug labels)

- [ ] Text mine drug labels

Also look into bringing that data into the Drug Index: "FDA provides bulk downloads at https://open.fda.gov/apis/drug/event/download/ These could be pre-loaded into the drug index by the pipeline to avoid the frontend having to make API calls."

**Comment by MichaelaEBI** [comment] 2019-03-12 23:11
Work in progress: 
openFDA notes from Eirini
A) Current query:
https://api.fda.gov/drug/event.json?search=patient.drug.medicinalproduct:' + drugName + '&count=patient.reaction.reactionmeddrapt.exact’
This returns the list under the tab “Analyzed Event Counts for Specified Drug” 
See example here (need to switch to 2nd tab):
https://openfda.shinyapps.io/LRTest/?t1=COPANLISIB&v1=patient.drug.openfda.generic_name&useexact=exact&start=1989-06-29&end=2018-09-13
We keep the first 20 and show the name and counts for each event.
e.g. https://www.targetvalidation.org/summary?drug=CHEMBL3218576
Criticism: includes self-reported events & doesn’t account for significance (is this adverse event significantly linked to the drug)
B) It might be more accurate to use their results based on one of their statistical methods: e.g. LRTest or PRR 
    Likelihood Ratio Test (LRT) Methodology is the one linked above. We could keep the significant hits (p-val,0.05) (while also extracting the nij variable (number of events)
    Proportional reporting ratio example here: https://openfda.shinyapps.io/RR_D/?t1=COPANLISIB&v1=patient.drug.openfda.generic_name. Seems to be considering many more as significant (compared to LRT)
Uncertain on query structure to get these…
C) Note that there is an option to check who reports the events. 
See here: https://open.fda.gov/apis/drug/event/explore-the-api-with-an-interactive-chart/
Maybe we can limit input to health professionals & pharmacists?
D) Option to download dataset for reproducibility:
Adverse Events files here: https://open.fda.gov/apis/downloads/
Instructions for downloads in general here: https://open.fda.gov/apis/drug/event/download/

Comment from Michaela: I agree that we should download/save data for reproducibility. It would be best if we don't have to download all the data and process it. If we could retrieve significant adverse events only that would be great.

**Comment by EPetsalaki** [comment] 2019-04-09 09:44
Note on part (C) of my notes:
The field to exclude self reported events is "primary.qualification"
Accepted values are 1,2,3,4,5, where:
1 = Physician
2 = Pharmacist
3 = Other health professional
4 = Lawyer
5 = Consumer or non-health professional

Example openFDA API query for counts of adverse events reported by physicians for the drug COPANLISIB: 
https://api.fda.gov/drug/event.json?search=primarysource.qualification:1+AND+patient.drug.medicinalproduct:COPANLISIB&count=patient.reaction.reactionmeddrapt.exact

The same, but for events reported by all health professionals:
https://api.fda.gov/drug/event.json?search=(primarysource.qualification:1+OR+primarysource.qualification:2+OR+primarysource.qualification:3)+AND+patient.drug.medicinalproduct:COPANLISIB&count=patient.reaction.reactionmeddrapt.exact

**Comment by d0choa** [comment] 2019-09-13 15:45
New implementation is soon to be released. "Investigation" is completed and the approach is setup using FAERS data from openFDA.
Closing this issue

**Closed by d0choa** 2019-09-13 15:45 UTC
Labels: Drug index, Priority: High
