### ISSUE TITLE
Target profile page rewrite: Build dashboard tab bar

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#240] opened 2018-11-02 13:42 UTC

**Comment by andrewhercules** [comment] 2018-11-27 09:54
### Use case(s)

1. As a user, I want to toggle between the Target Profile Overview and Associations View

### Component design

![dashboard-tab-bar](https://user-images.githubusercontent.com/7490258/49073263-f0109680-f229-11e8-86fd-040694f820cc.png)

**[Full size version](https://drive.google.com/open?id=1fpzZplo2PZHAkouCcOZpjCEEAT4F3xSN)**
 
### Key design and interaction notes

- For the active state when a user is on the Target Profile Overview (target profile page), please make the background purple (#7B196A), the text bold, and both the text and the gene icon white (#ffffff)
- For the active state when a user is on the Associations View, please make the background dark blue (#006593), the text bold, and both the text and the associations icon white (#ffffff)
- For the inactive state, please make the background white (#ffffff), the text regular weight, and both the text and relevant icon dark grey (#5A5F5F)

### Design assets

1. The icons are available on the [OT Core Platform Team Google Drive](https://drive.google.com/drive/folders/10gRFd-293HSra-p4czjQTWkYQQJAgHew)
1. Colour codes are available on the [OT Core Platform Team Google Drive](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)

**Comment by peatroot** [comment] 2019-10-01 08:27
@d0choa, suggest we close this as out of date? Icons now appear at top of entity pages instead.

**Comment by d0choa** [comment] 2019-10-01 08:52
We can close it as the problem is now different. We could still decide to include icons in the tab names but they would have to be different

**Closed by d0choa** 2019-10-01 08:52 UTC
Labels: React rewrite: TPP
