### ISSUE TITLE
Frontend crash for panel "RNA and protein baseline expression"

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#601] opened 2019-05-16 12:47 UTC
The panel "RNA and protein baseline expression" crashes after opening. 
Steps to reproduce:
1. go to https://www.targetvalidation.org/target/ENSG00000282608
2. open the "RNA and protein baseline expression" panel. Notice the error in the "Console" panel (e.g. in Chrome dev tools). See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/57854868-8bea8a80-77e9-11e9-829d-135c06a7814a.png)

**Comment by peatroot** [comment] 2019-05-16 13:30
See https://github.com/opentargets/platform/issues/127.

**Comment by pieterlukasse** [comment] 2019-06-11 10:49
Hi @LucaFumis , we tested the fix at https://github.com/opentargets/webapp/commit/f2e7039c682ccf90c4b321469760fd778023281f, but unfortunately the result is now that none of the 3 tabs are available, while there could be data in one of them. I heard from the users/testers that the fix causes ""No data for ENSG00000282608" to be displayed, even though there is "GTEx variability" data for ENSG00000282608. Can you confirm this? If yes, then the best solution would be to disable each of the tabs separately.

**Comment by LucaFumis** [comment] 2019-06-14 12:24
Hi @pieterlukasse yes, that's correct: as per latest fix we use the response for the "Summary" tab to enable/disable _all_ tabs. 
For the 2nd tab we load the Expression Atlas dependencies and that generates the widget and makes the call, so we don't access that response directly. I'll need to investigate it a bit, but I suspect we might only be able to enable/disable 1st and 3rd tab...

**Comment by pieterlukasse** [comment] 2019-06-21 15:52
hi @LucaFumis, thanks for the reply. Any updates on this one?

**Comment by LucaFumis** [comment] 2019-06-25 09:57
Hi @pieterlukasse, I haven't had the chance to look at this in more detail unfortunately - will try do after new release is out later this week / early next week.

Cheers,
Luca

**Comment by pieterlukasse** [comment] 2019-06-26 09:33
Sounds good @LucaFumis. Thanks for the update!

**Comment by fedde-s** [comment] 2019-07-04 15:19
Just to check—@LucaFumis, is it still on your list? The bug can still be reproduced in the version currently deployed to the public platform (3.13.1), listing that there's no data for this particular gene despite data being returned by the GTEx webservice calls.

**Comment by d0choa** [comment] 2019-07-04 17:24
Hi @fedde-s, we're trying to fix the original problem on the data regarding the wrong assembly. Since the issue is just preventing some data to be shown, we are aiming for the long-term solution. Bare with us and we'll try to get this sorted once the right data flows in

**Comment by fedde-s** [comment] 2019-07-05 09:14
Thanks for the update; I'll relay it to the people who were asking me about it :)

**Comment by d0choa** [comment] 2020-01-28 15:31
Still under investigation. Closing as duplicated from #127

**Closed by d0choa** 2020-01-28 15:31 UTC
Labels: Kind: Bug
