### ISSUE TITLE
Expression widget empty for ADORA3

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#127] opened 2018-09-17 15:19 UTC
When viewing the *RNA and protein baseline expression* widget on the target profile page, no data is shown, which is unexpected. This may be related to the 400 returned by a different call (https://www.ebi.ac.uk/gxa/json/baseline_experiments).

The page can be viewed at https://www.targetvalidation.org/target/ENSG00000282608.

**Comment by deniseOme** [comment] 2018-09-19 11:35
I have talked to Laura Huerta (Expression Atlas) regarding this.

There may be a problem in their pipeline. They are checking this as we speak. The gene has lower levels of expression but nevertheless should be picked up by them.

At any rate, the ADORA3 protein is shown in Protein Atlas and Illumina body map does show expression at its RNA level.

**Comment by deniseOme** [comment] 2018-09-19 12:54
Expression Atlas to check whether issue with low expressed genes missing baseline expression is widespread or a one off.

**Comment by peatroot** [comment] 2018-11-15 16:33
Any update on this @deniseOme?

**Comment by ElaineMcA** [comment] 2019-01-02 11:32
@ElaineMcA @MichaelaEBI - meeting scheduled w/Atlas team on 09Jan2019 to get update.

**Comment by deniseOme** [comment] 2019-01-02 19:43
Laura has mentioned en passant that the issue may be due to a "GRCh37 versus GRCh38 assembly" thingy.

Thanks @ElaineMcA for the update. I have just had a look at this and here is what I've found:

1) No baseline expression for ADORA3 (greyed-out in the page below):
https://www.ebi.ac.uk/gxa/genes/ensg00000282608?ds=%7B%22kingdom%22%3A%5B%22animals%22%5D%7D#differential

2) Expression Atlas, Ensembl (latest human assembly GRCh38) and ourselves have ADORA3 as ENSG00000282608 but Ensembl GRCh37 does not have ENSG00000282608 at all:
http://grch37.ensembl.org/Multi/Search/Results?q=ENSG00000282608;site=ensembl

3) ADORA3 in GRCh37 has the following Ensembl gene ID: ENSG00000121933

So the culprit here **may** be the wrong ID given to the same gene from one assembly to the other. 

At any rate, please make sure that Laura Huerta is in this meeting as she may have additional information on this. Or catch her as soon as possible as sadly she will be leaving the EBI soon.

**Comment by ElaineMcA** [comment] 2019-01-03 09:39
Thanks for further analysis, @deniseOme . Aware of Laura's departure, meeting scheduled does include Laura -  Agree that it is vital that knowledge is handed over and pipeline process documented before team members depart, she is happy to help with this as always.

**Comment by AsierGonzalez** [comment] 2019-01-18 10:20
**Update after @MichaelaEBI and I met Laura on 17/1/19:**

Basically, @deniseOme is right, the issue is because ADORA3 has different Ensembl ids in GRCh37 and GRCh38. More specifically, atlas do **NOT** rerun the baseline experiments after each Ensembl release because they lack the power to do so. Therefore, experiments added to baseline atlas before 2014 (when GRCh38 was released) do not contain information for new gene ids.

The solution would be for atlas to rerun the baseline experiments that were run with GRCH37. This should not take took long given that there are currently (Expression Atlas release 29 – November 2018) only 41 human baseline experiments compared to the 1191 differential experiments.

We will talk to Jonathan Manning from the atlas team who is supposed to be in charge of the baseline atlas.

**Comment by AsierGonzalez** [comment] 2019-08-01 08:55
Atlas will provide an updated baseline expression file for the 19.09 release that should fix this issue.

**Comment by AsierGonzalez** [comment] 2019-09-10 14:32
New file has been received but it needs to be processed so it won't be ready for 19.09, aiming at 19.11.

**Comment by andrewhercules** [comment] 2019-11-29 12:40
@AsierGonzalez and @deniseOme - was this issue resolved in 19.11 or should it be re-assigned to 20.02?

**Comment by AsierGonzalez** [comment] 2019-11-29 12:57
I'm afraid it wasn't, I still need to re-run the baseline expression pipeline. Let's target to do it for 20.02

**Comment by andrewhercules** [comment] 2019-11-29 12:58
Perfect - will move to 20.02 release

**Comment by AsierGonzalez** [comment] 2020-06-03 14:14
Baseline data has been updated for 20.06 and this gene has baseline expression information

**Closed** 2020-06-10 08:29 UTC
Labels: Kind: Bug, Kind: Data, Topic: Atlas
