### ISSUE TITLE
Remove Cancer Biomarker (Target Profile Page) codebase from platform-app

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1706] opened 2021-08-17 10:29 UTC
We want to remove Cancer Biomarker section from the target profile page.

Please remove all legacy code. [Example](https://github.com/opentargets/platform-app/tree/b330715b19a0f0d5a82b8fe696e6c28a2d57fe19/src/sections/target/CancerBiomarkers)

**Comment by andrewhercules** [comment] 2021-08-17 14:03
Ticket closed - duplicate of #1645

**Closed by andrewhercules** 2021-08-17 14:03 UTC
