### ISSUE TITLE
--val step hangs when logging level is DEBUG

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#517] opened 2019-03-27 11:15 UTC
The `--val` step hangs (more often) when logging level is configured to be DEBUG. When setting log level to INFO it will normally succeed.

**Comment by pieterlukasse** [comment] 2019-03-27 11:20
last log message + stack trace:
```
2019-03-27 10:58:06,998 mrtarget.common.EvidencesHelpers_63 DEBUG - called validate_evidence on_done from 63
^CProcess Process-5:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 335, in _map
    _run_task(f_task, params)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 304, in _run_task
    for x in params.input_queue:
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 233, in __iter__
    while not self.is_done():
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 258, in is_done
    return self.namespace.remaining == 0 and self.queue.empty()
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
    return callmethod('__getattribute__', (key,))
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-8:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 335, in _map
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 335, in _map
    _run_task(f_task, params)
    _run_task(f_task, params)
    self.run()
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 304, in _run_task
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 304, in _run_task
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    for x in params.input_queue:
    for x in params.input_queue:
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 233, in __iter__
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 233, in __iter__
    while not self.is_done():
    while not self.is_done():
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 258, in is_done
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 258, in is_done
    return self.namespace.remaining == 0 and self.queue.empty()
    return self.namespace.remaining == 0 and self.queue.empty()
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 335, in _map
    return callmethod('__getattribute__', (key,))
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    return callmethod('__getattribute__', (key,))
    kind, result = conn.recv()
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
KeyboardInterrupt
KeyboardInterrupt
    _run_task(f_task, params)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 304, in _run_task
    for x in params.input_queue:
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 233, in __iter__
    while not self.is_done():
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 258, in is_done
    return self.namespace.remaining == 0 and self.queue.empty()
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
    return callmethod('__getattribute__', (key,))
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process Process-7:
    kind, result = conn.recv()
Traceback (most recent call last):
KeyboardInterrupt
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 335, in _map
    _run_task(f_task, params)
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 304, in _run_task
    for x in params.input_queue:
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 236, in __iter__
    if self.pipeline_namespace.error:
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
    return callmethod('__getattribute__', (key,))
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/src/app/mrtarget/CommandLine.py", line 212, in <module>
    sys.exit(main())
  File "/usr/src/app/mrtarget/CommandLine.py", line 160, in main
    datasources_to_datatypes = data_config.datasources_to_datatypes)
  File "mrtarget/modules/Evidences.py", line 353, in process_evidences_pipeline
    results = reduce_tuple_with_sum(pr.to_iterable(pl_stage))
  File "mrtarget/common/EvidencesHelpers.py", line 197, in reduce_tuple_with_sum
    return functools.reduce(lambda x, y: (x[0] + y[0], x[1] + y[1]), iterable, (0, 0))
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 841, in _to_iterable
    for x in input_queue:
  File "/usr/local/lib/python2.7/site-packages/pypeln/process.py", line 236, in __iter__
    if self.pipeline_namespace.error:
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 1023, in __getattr__
    return callmethod('__getattribute__', (key,))
  File "/usr/local/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
KeyboardInterrupt
```

**Comment by afaulconbridge** [comment] 2019-03-27 12:50
Is this a duplicate of opentargets/platform#177 ? It seems like it is the same underlying problem to me

**Comment by pieterlukasse** [comment] 2019-03-27 12:53
yeah, perhaps one more for the collection. I don't think we had reported a possible association to the logging level yet. But now it seems we have enough evidence.

**Comment by afaulconbridge** [comment] 2019-03-27 13:56
Yes, this is becoming clearer. Do you mind if we close this ticket please? I don't think it adds any information above opentargets/platform#177

**Comment by pieterlukasse** [comment] 2019-03-27 15:38
closing, assuming to be duplicate of #177

**Closed** 2019-04-04 13:43 UTC
