### ISSUE TITLE
Project Score Profile page for Parp1 incorectlt links out to Parp11 

### ISSUE THREAD

**Issue by PruMM** [opentargets/platform#782] opened 2019-11-19 13:56 UTC
Please may you correct the linking above for PARP1

**Comment by PruMM** [comment] 2019-11-19 14:26
The same problem also affects 
RB1 whose project score profile page links out to the RB1CC instead of RB1

**Comment by d0choa** [comment] 2019-11-19 14:32
After preliminary investigations, there is an incomplete logic behind the construction of the link-outs implemented in the FE (webapp & platform-app).

Short-term, we need to double check that the link is only build if the first result of the search is an exact match. In the case of PARP1, there is no data for PARP1 (because it's an essential gene) but there is for PARP11. The expected behaviour is that we wouldn't have a link-out for PARP1.

Long-term, we will work with ProjectScore for them to provide mappings for every Ensembl gene or gene symbol to their internal gene ids.

**Comment by andrewhercules** [comment] 2019-11-29 14:52
Ticket closed as issue has been fixed

**Closed by andrewhercules** 2019-11-29 14:52 UTC
Labels: Status: Fixed
