### ISSUE TITLE
double check association based on GEL

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#131] opened 2018-09-19 12:09 UTC
Following a user support email:

We link ENSG00000196365 to Orphanet_2332 as can be seen here
https://www.targetvalidation.org/evidence/ENSG00000196365/Orphanet_2332

The papers reported in the page above however are all related to CODAS syndrome.

It seems the evidence ID for the ENSG00000196365-Orphanet_2332 is f19d8cb1ca44004beeb3fa7bd2ce77a0 (direct evidence) but the original data source (GEL) shows no association between those two entities:
https://panelapp.genomicsengland.co.uk/panels/285/gene/LONP1/

Could someone have a look at this please and comment? Is this a disease mapping issue?

**Comment by afaulconbridge** [comment] 2018-09-19 15:03
This issue comes to OpenTargets in the GEL API. The record for panel 285 (Intellectual disability) at https://panelapp.genomicsengland.co.uk/WebServices/search_genes/all/?panel_name=Intellectual disability for Gene Symbol LONP1 has a phenotype of "CODAS syndrome, 600373". 

@gkos-bio @MichaelaEBI Do we have a mechanism for reporting these issues to GEL?

**Comment by afaulconbridge** [comment] 2018-09-20 10:48
Ignore that previous comment - I was completely wrong. It's supposed to be "CODAS" so the API is correct. Sorry, my bad!

In the evidence file we generate (https://storage.googleapis.com/ot-releases/18.08/genomics_england-23-07-2018.json.gz) There are evidence between LONP1 and both CODAS and KBG - but in the panel it is only associated between LONP1 and CODAS. KBG is mentioned in the panel, but associated with gene ANKRD11. 

The evidence was last generated in July against panel 2.207 and the current version is 2.447. So it is possible the panel has changed since the evidence was last updated. I'm going to try to regenerate the evidence and see if the issue persists.

**Comment by deniseOme** [comment] 2018-09-20 11:26
Thanks @afaulconbridge! I wonder if the issue could be due to the fact that both CODAS and KBG are children terms of https://www.targetvalidation.org/disease/Orphanet_330206 and the use of indirect evidence?

http://blog.opentargets.org/2017/04/25/direct-versus-indirect-evidence-should-you-care/

I've checked OMIM and other resources and don't seem to find direct of association between KBG and LONP1. Let's see if GEL has updated this then since v.2.207.

**Comment by afaulconbridge** [comment] 2018-09-20 14:40
@deniseOme Hmm, thats a good idea but it looks like this issue is present in the raw evidence generated from GEL PanelApp, whereas the direct vs indirect propegation is applied later in the pipeline. It does make me wonder if the issue is coming from the ontology mapping process somewhere (OLS, Zooma?) since KBG and CODAS both use words like "syndrome", "anomalies" and "dental".

**Comment by deniseOme** [comment] 2018-09-20 14:42
I see...Ok, so indirect/direct is not the culprit.
Note that the two diseases share some phenotypes. Dunno if this can impact the disease mapping.

Looking forward to hearing from @gkos-bio @MichaelaEBI.

**Comment by MichaelaEBI** [comment] 2018-09-20 23:02
Looking at the PanelApp and the code, it would be good to have an intermediate file that lists all the mappings we get when running the pipeline so that we can troubleshoot these kind of issues quickly. There are 'only' ~200 panels, so it should even be manageable to look through the list to double check mappings.

This summary page lists the 6 panels that LONP1 belongs to and the phenotypes for each panel https://panelapp.genomicsengland.co.uk/panels/entities/LONP1

@gkos-bio are only the phenotypes used for disease mapping or the panel names as well?

**Comment by afaulconbridge** [comment] 2018-09-21 14:45
Now that I've been able to successfully re-run the evidence generation (thanks to @gkos-bio for pointers!) I can see that in the latest version of panel 285 LONP1 is only linked to CODAS, which matches what can be seen in the GEL web pages and API.

I'll upload the newly generated evidence for GEL into the ot-releases bucket so it can go into the 18.10 release. We should double-check this as part of the QC to make sure its fixed in the final product.

**Comment by deniseOme** [comment] 2018-09-21 15:03
Thanks @afaulconbridge & @gkos-bio. Glad to hear. Do you know what exactly went wrong?

**Comment by afaulconbridge** [comment] 2018-09-24 09:11
I've realised that the new version I generated has far fewer associations (~7k down from ~32k) so I need to take another look at the process and see why things have gone missing. I suspect I just haven't run it correctly, rather than any specific problems.

**Comment by afaulconbridge** [comment] 2018-10-02 11:40
I've taken another look - it seems like the last version had a lot of duplication, and the new version wasn't fully including some ontologies. There is still a difference from 16,228 to 11,079 but looking at a small sample of evidences, I think those are "natural" changes from source. I'll revisit the GEL mappings post-EFO3/MONDO which should raise those numbers again. 

I'm closing this specific issue as the data has been fixed.

**Closed by afaulconbridge** 2018-10-02 11:40 UTC
Labels: Kind: Bug, Kind: Data, Source: Takeda
