### ISSUE TITLE
Drug index : I : Refactor chembl.py plug-in in ck_compound branch to read data from file

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#310] opened 2018-11-21 12:14 UTC
The chembl.py module currently queries the ChEMBL API to retrieve compounds with clinical trial data and compounds with mode of action annotation. To make the pipeline reproducible, the API call responses should be saved in files that are read in by the chembl.py module to generate the drug index.

**Comment by afaulconbridge** [comment] 2019-01-30 12:20
This is a duplicate of opentargets/platform#329 Remove external API use: gene plugin Chembl

**Comment by MichaelaEBI** [comment] 2019-01-30 17:49
Not really a duplicate, rather overlapping - I will still have to re-factor this module to work with the files Cinzia is generating.

**Comment by afaulconbridge** [comment] 2019-05-15 10:59
Done in branch `af-drug` in `data_pipeline`

**Comment by ElaineMcA** [comment] 2019-07-08 15:01
Closing as deployed via 19.06 release.

**Closed by ElaineMcA** 2019-07-08 15:01 UTC
Labels: Drug index, Kind: Data, Status: Fixed, Topic: Pipeline
