### ISSUE TITLE
Invalid ChEMBL evidence: "Multiple genes with uniprot P69905"

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#737] opened 2019-09-20 14:09 UTC
@mkarmona has noticed that ChEMBL evidence for `EFAPROXIRAL` associating HBA1 with lung carcinoma has disappeared.

**19.06**
![Screenshot 2019-09-20 at 15 10 57](https://user-images.githubusercontent.com/11410715/65333765-ff960d00-dbb8-11e9-934b-c76a87f3ca0b.png)

**19.09 QA**
![Screenshot 2019-09-20 at 15 11 19](https://user-images.githubusercontent.com/11410715/65333810-12104680-dbb9-11e9-9d03-23d463eec445.png)

We have found that the evidence strings are considered invalid by the pipeline and the explanation is "Multiple genes with uniprot P69905".

HBA1 and HBA2 are two subunits of the same protein and they both have P69905 as their `uniprot_id`. Additionally, HBA2 is a `symbol_synonym` of HBA1 but it does not happen vice versa.
It is biologically correct to have two different genes annotated with the same Uniprot accession so the data pipeline should be able to handle this situation.

**Comment by afaulconbridge** [comment] 2019-09-20 15:31
Can you confirm they have different unique association fields?

**Comment by AsierGonzalez** [comment] 2019-09-20 15:39
There are two evidence strings with the same unique association fields:
```
{
  "chembl_molecule": "http://identifiers.org/chembl.compound/CHEMBL18901",
  "url": "https://clinicaltrials.gov/search?id=%22NCT00055887%22",
  "disease_id": "http://www.ebi.ac.uk/efo/EFO_0001071",
  "target_id": "http://identifiers.org/uniprot/P69905"
}
```

**Comment by AsierGonzalez** [comment] 2019-11-25 14:11
Hi @andrewhercules, are there any updates for this? At the moment this does not seem to be a data issue, I would need an update from the BE team (apparently @afaulconbridge) to know if we need to ask ChEMBL to make any changes to evidence.

**Comment by andrewhercules** [comment] 2019-11-26 09:15
@AsierGonzalez, I wonder if it is a data issue because in 19.09, those two evidence strings are now associated with [HBB](https://www.targetvalidation.org/target/ENSG00000244734), which I believe is the parent complex for both HBA1 and HBA2. 

![Screenshot 2019-11-25 at 17 21 13](https://user-images.githubusercontent.com/7490258/69562884-015cc200-0fa8-11ea-98ba-09248b0336a7.png)

This is also reflected on ChEMBL's [profile page for the drug in question Efaproxiral](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL18901/).

![Screenshot 2019-11-26 at 09 13 47](https://user-images.githubusercontent.com/7490258/69615602-129be200-102d-11ea-9c7d-0a60870d5377.png)

Perhaps ChEMBL updated the curation of this compound?

If ChEMBL have not updated the curation of the compound, I would assume that they would generate 4 evidence strings - two for HBA1 and HBA2 - similar to the duplication of evidence we see for other compounds that are associated with a protein complex (e.g. [Metformin](https://www.targetvalidation.org/summary?drug=CHEMBL1431) and [type II diabetes mellitus](https://www.targetvalidation.org/disease/EFO_0001360)).

**Comment by AsierGonzalez** [comment] 2019-11-26 15:24
@andrewhercules, the reason I don't think this is (strictly) a data issue is because the evidence strings for this drug didn't change between 19.06 and 19.09 (and same for 19.11 as the file hasn't changed). In total there are 10 evidence strings, the protein targets are HBA1 and HBB and lung carcinoma is one of the associated diseases.

**Comment by AsierGonzalez** [comment] 2019-11-27 16:45
A more detailed look into the the data suggests that this issue is not caused by the data:

1. Targets in ChEMBL evidence are identified by UniProt ids
2. In this case there 10 evidence strings for `EFAPROXIRAL` and the associated targets are  http://identifiers.org/uniprot/P68871 (HBB) and http://identifiers.org/uniprot/P69905 (HBA1 and HBA2)

Therefore, the evidence for P68871 should be showed both for HBA1 (ENSG00000206172) and HBA2 (ENSG00000188536).

This may be what the error "Multiple genes with uniprot P69905" may mean but it should not be an issue that multiple genes share the same UniProt id.

**Comment by AsierGonzalez** [comment] 2020-01-09 10:38
This is probably related to #801 as it is caused by two genes being annotated with the same UniProt  id. Assigning @cmalangone to it.

**Comment by d0choa** [comment] 2020-01-28 18:01
Closing as duplicate of #801

**Closed by d0choa** 2020-01-28 18:01 UTC
