### ISSUE TITLE
Can we simplify literature references to just pmids?

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#284] opened 2018-11-13 16:58 UTC
Many evidence strings contain a field `literature.references`, which is an array of objects, each of which is of the form:
```
{
  "lit_id": "http://europepmc.org/abstract/MED/17146052"
}
```

Is there any reason not to just format `literature.references` as a list of pubmed ids (ie. just `17146052` above)?

**Comment by mkarmona** [comment] 2018-11-13 17:56
@peatroot this was like that to show the full link and pointing to europepmc instead to pubmed. https://www.nlm.nih.gov/bsd/difference.html

**Comment by mkarmona** [comment] 2018-11-13 17:58
@peatroot we could just return a list of pub uris but then I should have a look whether we use that object to inject just not the uri but more fields

**Comment by afaulconbridge** [comment] 2018-11-13 19:20
Why was this closed? I don't see a definitive answer beyond "maybe".

**Comment by d0choa** [comment] 2020-01-29 17:48
This is part of a bigger task that will imply establishing data submission guidelines for literature references. The issue is still valid but closing this ticket for tracking purposes

**Closed by d0choa** 2020-01-29 17:48 UTC
Labels: Kind: Question, Topic: JSON
