### ISSUE TITLE
Data pipeline makefile docs default SCHEMA_VERSION to `master`

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#305] opened 2018-11-19 14:22 UTC
If I follow the instructions in [the markdown file](https://github.com/opentargets/data_pipeline/tree/18.10.2#using-the-makefile), or the commands in the [GCP script](https://github.com/opentargets/data_pipeline/blob/18.10.2/scripts/run_on_gcp.sh#L138) (MrTarget 18.10.2), I find no mention of the [`SCHEMA_VERSION` variable](https://github.com/opentargets/data_pipeline/blob/18.10.2/Makefile#L16) used by the Makefile.

This defaults the schema version to `master`, while I was informed that the appropriate version to use for release 18.10 of the data and software is `1.2.8`. Is this missing in the documentation?

**Comment by afaulconbridge** [comment] 2018-11-20 10:34
The way the schema version is set is slightly complicated for 18.10.2 - in future it will be simpler once opentargets/platform#146 is completed.

The [GCP script](https://github.com/opentargets/data_pipeline/blob/18.10.2/scripts/run_on_gcp.sh)  creates a `docker-compose.yml` file within the newly created virtual machine, and within that docker file there is a specification for running a pipeline container (`mrtarget`). That container specification sets an environment variable on the container `SCHEMA_VERSION` on [line 115](https://github.com/opentargets/data_pipeline/blob/18.10.2/scripts/run_on_gcp.sh#L115). This environment file is passed to Make, and the [Makefile line 16](https://github.com/opentargets/data_pipeline/blob/18.10.2/Makefile#L16) specifies that this environment variable should be set to master *only if it does not already exist*. Since it will exist within the container on the virtual machine, then this line will do nothing. 

The schema version is passed to the pipeline with a `--schema-version` argument within the Makefile, and should use the environment variable specified in the docker-compose file created by the script within the virtual machine.

Hopefully you can follow all of that! As I said, it is complicated at the moment, but should be simpler once opentargets/platform#146 is completed. I'm re-running the [GCP script](https://github.com/opentargets/data_pipeline/blob/18.10.2/scripts/run_on_gcp.sh) from scratch to confirm it is working as intended, and I'll update this ticket tomorrow when it will have some results.

**Comment by fedde-s** [comment] 2018-11-20 10:50
Thanks for the reply! I now understand that, in order to run the pipeline internally without GCP, the version I should pass to be as consistent as possible is *not* 1.2.8, but rather 1.3.0. This is what I could not infer from the README.

Is that because `master` is a safe default when running the the latest MrTarget release, identical to 1.3.0 until the moment next release becomes official, or should I make a PR to document the arg/envvar in the non-GCP sections of the README?

**Comment by fedde-s** [comment] 2018-11-20 11:02
Or maybe even simpler: just like the supported data release for MrTarget 18.10.2 is hard-coded as URLs in the Makefile, I could hard-code the schema version as well.

**Comment by afaulconbridge** [comment] 2018-11-21 11:22
The JSON schema versioning is complicated with a number of issues:
- 1.2.8 and previous were branches, not versions so were mutable over time. 
- Its split over multiple files, with absolute URLs references. In many cases branches referred to master (e.g. with 1.2.8 before Nov 2, 2018) which further makes it more changing than it should be.
- in 1.2.8 and lower the version of the schema had to be specified within the json documents that were validated against it. This meant that incremental change was impossible.
- there isn't a single schema, rather a collection of schemas for different data types but in some cases different data types validate against the same schema (e.g. `somatic mutation`, `affected pathway`, and `genetic literature` all validate against the `literature curated` schema). This is additionally complicated because a single data source may have multiple data types.

For 1.3.0 the references have been made relative, and it was a tag not a branch. So that makes it behave more like normal software releases, and is backwards compatible with 1.2.8 in terms of the documents it validated. So while 1.2.8 was indeed the version used for the 18.10 core release, for 18.10.2 re-runs the 1.3.0 version is more reproducible and will give the same results.

Early in 2019 we want to move to a single combined schema (using "oneOf" restrictions to ensure the different data types have different requirements) and combine the various files into one to avoid the need for cross-references. You can see this work in progress on the `af-cleanup` branch at https://github.com/opentargets/json_schema/tree/af-cleanup . When the configuration for the pipeline is improved as per issue opentargets/platform#146 we can think about putting the schema inside the docker image for particular releases and referencing it with a `file://` URL, which will make this even simpler and more reproducible.

We've got an on-going branch to improve the readme documentation at https://github.com/opentargets/data_pipeline/blob/readme_update/README.md - feedback and improvements welcome!

**Comment by afaulconbridge** [comment] 2018-11-21 11:54
I've re-run the GCP script and it does indeed use 1.3.0 of the schema as intended, so closing this issue.

**Closed by afaulconbridge** 2018-11-21 11:54 UTC
Labels: Priority: High, Source: Sanofi, Source: Takeda

**Comment by fedde-s** [comment] 2018-11-21 17:01
In that case, in order to resolve this issue, following the documentation for non-GCP docs for 18.10 should use 1.3.0. 1.2.8 does *not* work, and causes all evidence data except Europe PMC to be marked as invalid. I will amend the README rather than the Makefile, to have as little effect as possible on your use-case.

**Comment by fedde-s** [comment] 2018-11-21 17:16
In hindsight, setting it as the default within the Makefile reduces the number of places that duplicate the number, which is probably more maintainable. It wouldn't affect the ability to override it with a different number during testing/development.
